# Generated by Django 5.2.8 on 2025-11-22 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='EmissionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('co2_emissions', models.FloatField(help_text='CO2 emissions in million tonnes')),
                ('methane_emissions', models.FloatField(blank=True, help_text='CH4 emissions in million tonnes', null=True)),
                ('nitrous_oxide', models.FloatField(blank=True, help_text='N2O emissions in million tonnes', null=True)),
                ('total_ghg', models.FloatField(help_text='Total GHG emissions in CO2 equivalent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ghg.country')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('country', 'year')},
            },
        ),
    ]
