# Generated by Django 5.1.2 on 2025-11-24 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('1', 'Scope 1 - Direct Emissions'), ('2', 'Scope 2 - Indirect Emissions (Energy)'), ('3', 'Scope 3 - Other Indirect Emissions')], max_length=1)),
                ('category', models.CharField(help_text='e.g., stationary, mobile, electricity', max_length=50)),
                ('source', models.CharField(help_text='e.g., diesel, natural-gas', max_length=100)),
                ('source_name', models.CharField(help_text='Display name of source', max_length=200)),
                ('activity_data', models.FloatField(help_text='Amount of activity')),
                ('unit', models.CharField(help_text='Unit of measurement', max_length=20)),
                ('emission_factor', models.FloatField(help_text='Emission factor used')),
                ('emissions_kg', models.FloatField(help_text='Total emissions in kg CO2e')),
                ('emissions_tons', models.FloatField(help_text='Total emissions in tons CO2e')),
                ('country', models.CharField(default='global', help_text='Country for emission factors', max_length=50)),
                ('reference', models.TextField(blank=True, help_text='Reference source for emission factor', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('supplier', models.CharField(blank=True, help_text='Supplier name', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emission Record',
                'verbose_name_plural': 'Emission Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
