# Generated by Django 5.2.8 on 2025-11-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_supplier_data(apps, schema_editor):
    """Copy old supplier CharField data to supplier_old before conversion"""
    EmissionRecord = apps.get_model('ghg', 'EmissionRecord')
    db_alias = schema_editor.connection.alias
    
    # Copy supplier to supplier_old
    for record in EmissionRecord.objects.using(db_alias).all():
        if hasattr(record, 'supplier') and record.supplier:
            record.supplier_old = str(record.supplier)
            record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0002_emissionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add supplier_old field
        migrations.AddField(
            model_name='emissionrecord',
            name='supplier_old',
            field=models.CharField(blank=True, help_text='Supplier name (deprecated)', max_length=200, null=True),
        ),
        
        # Step 2: Copy data from supplier to supplier_old
        migrations.RunPython(copy_supplier_data, migrations.RunPython.noop),
        
        # Step 3: Remove old supplier field
        migrations.RemoveField(
            model_name='emissionrecord',
            name='supplier',
        ),
        
        # Step 4: Create Supplier model
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Supplier/Vendor name', max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('supplier_type', models.CharField(blank=True, help_text='e.g., Energy, Fuel, Transportation', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        
        # Step 5: Add new supplier ForeignKey field
        migrations.AddField(
            model_name='emissionrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier/Vendor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ghg.supplier'),
        ),
    ]
