# Generated by Django 5.2.8 on 2025-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0003_add_supplier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, help_text='Country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax/VAT number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, help_text='Company website', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Full address', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Primary contact name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Primary contact email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(blank=True, help_text='Activity/Type: Energy, Fuel, Transportation, etc.', max_length=100, null=True),
        ),
    ]
