# Generated by Django 5.2.8 on 2025-11-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0004_add_supplier_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='industry_type',
            field=models.CharField(blank=True, help_text='Industry type (for specific sources)', max_length=100, null=True),
        ),
    ]
