# Generated by Django 5.2.8 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0005_add_industry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='fuel_name',
            field=models.CharField(blank=True, help_text='Fuel name (for Off-Road)', max_length=100, null=True),
        ),
    ]
