# Generated by Django 5.2.8 on 2025-12-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0006_add_fuel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Name of material/product', max_length=200)),
                ('category', models.CharField(help_text='Category (e.g., purchased-goods, stationary)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('emission_factor', models.FloatField(help_text='Emission factor value (kg CO2e per unit)')),
                ('unit', models.CharField(help_text='Unit of measurement (kg, liters, m3, etc.)', max_length=20)),
                ('source_reference', models.TextField(blank=True, help_text='Reference/source of this emission factor (e.g., supplier certificate, LCA study)', null=True)),
                ('certificate_file', models.FileField(blank=True, help_text='Upload certificate or documentation', null=True, upload_to='emission_certificates/')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, help_text='Supplier who provided this factor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_factors', to='ghg.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_factors', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Emission Factor',
                'verbose_name_plural': 'Custom Emission Factors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(help_text='Name of requested material/source', max_length=200)),
                ('category', models.CharField(help_text='Category (e.g., purchased-goods, stationary)', max_length=50)),
                ('description', models.TextField(help_text="Description of the material and why it's needed")),
                ('suggested_factor', models.FloatField(blank=True, help_text="User's suggested emission factor (if known)", null=True)),
                ('suggested_unit', models.CharField(blank=True, help_text='Suggested unit', max_length=20, null=True)),
                ('suggested_source', models.TextField(blank=True, help_text='Source of suggested factor', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved - Factor Added'), ('rejected', 'Rejected'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes/response', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('added_to_system', models.BooleanField(default=False)),
                ('system_source_key', models.CharField(blank=True, help_text='Key in emission_factors.py if added to system', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Material Request',
                'verbose_name_plural': 'Material Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
