# Generated by Django 5.2.8 on 2025-12-29 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0007_customemissionfactor_materialrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, help_text='Legal name of organization', max_length=200, null=True)),
                ('industry', models.CharField(blank=True, help_text='Industry type or NAICS code', max_length=100, null=True)),
                ('reporting_period', models.CharField(blank=True, help_text='Reporting period (e.g., 2025-01-01 to 2025-12-31)', max_length=100, null=True)),
                ('boundary_approach', models.CharField(blank=True, choices=[('operational_control', 'Operational Control'), ('financial_control', 'Financial Control'), ('equity_share', 'Equity Share')], help_text='Consolidation approach', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context for the report', null=True)),
                ('share_org_profile', models.BooleanField(default=True, help_text='User consented to share organization profile')),
                ('share_boundary', models.BooleanField(default=True, help_text='User consented to share reporting boundary')),
                ('share_data_sources', models.BooleanField(default=False, help_text='User consented to share data sources info')),
                ('share_projects', models.BooleanField(default=False, help_text='User consented to share projects/initiatives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_extra_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Extra Information',
                'verbose_name_plural': 'Report Extra Information',
            },
        ),
    ]
