# Generated by Django 5.2.8 on 2026-01-02 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0008_reportextrainfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Industry name', max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='Industry code (e.g., NAICS)', max_length=20, null=True)),
                ('description', models.TextField(blank=True, help_text='Industry description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this industry type active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who requested this industry type', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Industry Type',
                'verbose_name_plural': 'Industry Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(help_text='Requested industry name', max_length=200)),
                ('industry_code', models.CharField(blank=True, help_text='Industry code if known', max_length=20, null=True)),
                ('description', models.TextField(help_text='Description of the industry')),
                ('business_context', models.TextField(blank=True, help_text='How this industry relates to their business', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approved_industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ghg.industrytype')),
            ],
            options={
                'verbose_name': 'Industry Request',
                'verbose_name_plural': 'Industry Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
