# Generated by Django 5.2.8 on 2026-01-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0002_make_email_unique'),
        ('ghg', '0009_add_industry_models'),
    ]

    operations = [
    ]
