# Generated by Django 5.2.8 on 2026-01-26 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0009_add_industry_models'),
    ]

    operations = [
    ]
