# Generated by Django 5.2.8 on 2026-01-26 14:16

import ghg.models
import ghg.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0012_add_emissionrecord_proof_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customemissionfactor',
            new_name='ghg_custome_user_id_00a9ef_idx',
            old_name='ghg_customem_user_id_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ghg_emissio_user_id_31e751_idx',
            old_name='ghg_emissio_user_id_created_idx',
        ),
        migrations.RenameIndex(
            model_name='emissionrecord',
            new_name='ghg_emissio_user_id_62662c_idx',
            old_name='ghg_emissio_user_id_scope_idx',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='added_to_system',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='category',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='material_name',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='suggested_factor',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='suggested_source',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='suggested_unit',
        ),
        migrations.RemoveField(
            model_name='materialrequest',
            name='system_source_key',
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional information (max 2000 characters)', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='name',
            field=models.CharField(default='Unknown', help_text='Name of requested item', max_length=200),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='request_type',
            field=models.CharField(choices=[('material', 'Material'), ('industry', 'Industry Type'), ('emission_factor', 'Emission Factor')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='category',
            field=models.CharField(help_text='Category (e.g., fuel, electricity)', max_length=100),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Certificate or supporting document (PDF, DOC, DOCX - Max 10MB)', null=True, upload_to=ghg.models.secure_upload_path, validators=[ghg.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='description',
            field=models.TextField(blank=True, help_text='Description and methodology', null=True),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='factor_value',
            field=models.FloatField(help_text='Emission factor (kg CO2e per unit)'),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='name',
            field=models.CharField(help_text='Factor name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='reference_source',
            field=models.CharField(blank=True, help_text='Reference source', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customemissionfactor',
            name='unit',
            field=models.CharField(help_text='Unit (e.g., liter, kWh, kg)', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes', null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='description',
            field=models.TextField(default='', help_text='Detailed description'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['user', 'status'], name='ghg_materia_user_id_5bd0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['request_type', 'status'], name='ghg_materia_request_9a6e0f_idx'),
        ),
    ]
