# Generated by Django 5.2.8 on 2026-02-02 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0014_fix_materialrequest_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_number', models.CharField(choices=[('1', 'Scope 1 - Direct Emissions'), ('2', 'Scope 2 - Indirect Emissions (Energy)'), ('3', 'Scope 3 - Other Indirect Emissions')], max_length=1, unique=True, verbose_name='Scope Number')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('icon', models.CharField(default='🔥', max_length=50, verbose_name='Icon/Emoji')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color (Hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emission Scope',
                'verbose_name_plural': 'Emission Scopes',
                'ordering': ['scope_number'],
            },
        ),
        migrations.CreateModel(
            name='EmissionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Category Code')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('icon', models.CharField(default='📊', max_length=50, verbose_name='Icon/Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('methodology_notes', models.TextField(blank=True, null=True, verbose_name='Methodology Notes')),
                ('reference_standard', models.CharField(blank=True, max_length=200, null=True, verbose_name='Reference Standard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ghg.emissionscope', verbose_name='Scope')),
            ],
            options={
                'verbose_name': 'Emission Category',
                'verbose_name_plural': 'Emission Categories',
                'ordering': ['scope', 'display_order', 'name_en'],
                'unique_together': {('scope', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Source Code')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_fa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('description_fa', models.TextField(blank=True, null=True, verbose_name='Description (Persian)')),
                ('default_unit', models.CharField(help_text='e.g., liters, kWh, kg', max_length=50, verbose_name='Default Unit')),
                ('alternative_units', models.JSONField(blank=True, default=list, help_text='JSON array of alternative units', verbose_name='Alternative Units')),
                ('icon', models.CharField(default='⚡', max_length=50, verbose_name='Icon/Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('requires_industry_type', models.BooleanField(default=False, verbose_name='Requires Industry Type')),
                ('requires_fuel_name', models.BooleanField(default=False, verbose_name='Requires Fuel Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ghg.emissioncategory', verbose_name='Category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emission Source',
                'verbose_name_plural': 'Emission Sources',
                'ordering': ['category', 'display_order', 'name_en'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionFactorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='global', help_text="ISO country code or 'global'", max_length=10, verbose_name='Country Code')),
                ('country_name', models.CharField(default='Global', max_length=100, verbose_name='Country Name')),
                ('factor_value', models.FloatField(help_text='kg CO2e per unit', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Emission Factor')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('co2_factor', models.FloatField(blank=True, null=True, verbose_name='CO2 Factor')),
                ('ch4_factor', models.FloatField(blank=True, null=True, verbose_name='CH4 Factor')),
                ('n2o_factor', models.FloatField(blank=True, null=True, verbose_name='N2O Factor')),
                ('reference_source', models.CharField(blank=True, help_text='e.g., IPCC 2006, DESNZ 2024', max_length=500, null=True, verbose_name='Reference Source')),
                ('reference_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Reference Year')),
                ('methodology', models.TextField(blank=True, null=True, verbose_name='Methodology')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Valid From')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Valid To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default Factor')),
                ('uncertainty_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Uncertainty %')),
                ('data_quality_rating', models.CharField(choices=[('high', 'High Quality'), ('medium', 'Medium Quality'), ('low', 'Low Quality'), ('estimated', 'Estimated')], default='medium', max_length=20, verbose_name='Data Quality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_factors', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_factors', to='ghg.emissionsource', verbose_name='Emission Source')),
            ],
            options={
                'verbose_name': 'Emission Factor Data',
                'verbose_name_plural': 'Emission Factor Data',
                'ordering': ['source', 'country_code', '-reference_year'],
            },
        ),
        migrations.CreateModel(
            name='EmissionCalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_data', models.FloatField(verbose_name='Activity Data')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('calculated_emissions_kg', models.FloatField(verbose_name='Emissions (kg CO2e)')),
                ('calculation_method', models.CharField(default='direct', max_length=100, verbose_name='Calculation Method')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logs', to=settings.AUTH_USER_MODEL)),
                ('factor_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ghg.emissionfactordata')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ghg.emissionsource')),
            ],
            options={
                'verbose_name': 'Calculation Log',
                'verbose_name_plural': 'Calculation Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionfactordata',
            index=models.Index(fields=['source', 'country_code', 'is_active'], name='ghg_emissio_source__e89b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactordata',
            index=models.Index(fields=['is_default', 'is_active'], name='ghg_emissio_is_defa_1d9acf_idx'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculationlog',
            index=models.Index(fields=['user', '-created_at'], name='ghg_emissio_user_id_f952a0_idx'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculationlog',
            index=models.Index(fields=['source', '-created_at'], name='ghg_emissio_source__d2282f_idx'),
        ),
    ]
