# Generated by Django 5.2.5 on 2026-02-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghg', '0015_emissionscope_emissioncategory_emissionsource_and_more'),
    ]

    operations = [
        # Rename EmissionScope fields
        migrations.RenameField(
            model_name='emissionscope',
            old_name='name_fa',
            new_name='name_tr',
        ),
        migrations.RenameField(
            model_name='emissionscope',
            old_name='description_fa',
            new_name='description_tr',
        ),
        # Rename EmissionCategory fields
        migrations.RenameField(
            model_name='emissioncategory',
            old_name='name_fa',
            new_name='name_tr',
        ),
        migrations.RenameField(
            model_name='emissioncategory',
            old_name='description_fa',
            new_name='description_tr',
        ),
        # Rename EmissionSource fields
        migrations.RenameField(
            model_name='emissionsource',
            old_name='name_fa',
            new_name='name_tr',
        ),
        migrations.RenameField(
            model_name='emissionsource',
            old_name='description_fa',
            new_name='description_tr',
        ),
    ]
