# Generated by Django 5.2.8 on 2026-09-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghg", "0016_rename_fa_to_tr_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emissioncategory",
            name="description_tr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (Turkish)"
            ),
        ),
        migrations.AlterField(
            model_name="emissioncategory",
            name="name_tr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name (Turkish)"
            ),
        ),
        migrations.AlterField(
            model_name="emissionscope",
            name="description_tr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (Turkish)"
            ),
        ),
        migrations.AlterField(
            model_name="emissionscope",
            name="name_tr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name (Turkish)"
            ),
        ),
        migrations.AlterField(
            model_name="emissionsource",
            name="description_tr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (Turkish)"
            ),
        ),
        migrations.AlterField(
            model_name="emissionsource",
            name="name_tr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name (Turkish)"
            ),
        ),
    ]
