# Generated by Django 5.2.8 on 2026-09-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ghg", "0017_turkish_field_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrytype",
            name="name_tr",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Name (Turkish)"
            ),
        ),
    ]
